server:
  port: 8092

spring:
  application:
    name: order-service
  datasource:
    type: org.postgresql.jdbc2.optional.SimpleDataSource
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:mysecretpassword}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/db_products_app}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        default_schema: products
