server:
  port: ${PORT:8091}

spring:
  application:
    name: ${APP_NAME:todo}
  datasource:
    username: ${DB_USERNAME:todo_admin}
    password: ${DB_PASSWORD:todoapp}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/db_todo}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
    endpoints:
        web:
            exposure:
                include: ['health', 'prometheus']
