server:
  port: 8093

spring:
  application:
    name: notification-service
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:rabbituser}
    password: ${RABBITMQ_PASSWORD:rabbitpassword}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:library-app}
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
