version: '3.7'

networks:
  pocketnet:
    name: network-todo-app-observability
    driver: bridge

services:
  todo-app-nginx:
    container_name: prod-todo-app-nginx
    image: todo-app-nginx:1.0
    ports:
      - "80:80"
    networks:
      - pocketnet

  todo-app-api:
    container_name: prod-todo-app-api
    image: todo-app-api:1.1
    ports:
      - "8080:8080"
    environment:
      PORT: ${PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: ${DB_URL}
    networks:
      - pocketnet

  todo-app-db:
    container_name: prod-todo-app-db
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - pocketnet
