# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile docs: https://developer.hashicorp.com/vagrant/docs/vagrantfile
Vagrant.configure("2") do |config|

  # Base box to use
  # You can find more boxes at https://portal.cloud.hashicorp.com/vagrant/discover
  config.vm.box = "bento/ubuntu-22.04"

  # VM settings
  config.vm.provider "virtualbox" do |vb|
    vb.name = "vagrant-ubuntu-22.04"
    vb.cpus = 2
    vb.memory = "1024"
    vb.gui = true
  end

  # Run shell commands to setup the VM
  config.vm.provision "shell", inline: <<-SHELL
    # Installing g++ compiler
    apt-get update
    apt-get install -y g++
    # Installing Visual Studio Code
    apt-get install wget gpg -y
    wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
    install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg
    echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" |sudo tee /etc/apt/sources.list.d/vscode.list > /dev/null
    rm -f packages.microsoft.gpg
    apt-get install apt-transport-https -y
    apt-get update
    apt-get install code -y
    # Installing a GUI
    apt-get install lubuntu-desktop -y
  SHELL
end
