scrape_configs:
  - job_name: 'TodoAppMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['prod-todo-app-api:8080']
        labels:
          application: 'My Spring Boot Application'
