server:
  port: 8092

spring:
  application:
    name: borrowing-service
  datasource:
    type: org.postgresql.jdbc2.optional.SimpleDataSource
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:mysecretpassword}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/db_library_app}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${KC_CLIENT_ID:borrowing}
            client-secret: ${KC_CLIENT_SECRET:VNoGoN7zk561dEAkQ2DHS4DOOHXBL461}
            authorization-grant-type: client_credentials
            provider: keycloak
            scope: openid
        provider:
          keycloak:
            issuer-uri: ${KC_ISSUER_URI:http://localhost:8080/realms/library-app}
            user-name-attribute: preferred_username
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:rabbituser}
    password: ${RABBITMQ_PASSWORD:rabbitpassword}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:library-app}
